const messages: Record<string, string> = {
    Id: 'ID',
    State: '状态',
    Home: '首页',
    Complete: '完成',
    Edit: '编辑',
    Add: '新增',
    Info: '查看详情',
    Delete: '删除',
    Refresh: '刷新',
    Operate: '操作',
    Confirm: '确认',
    Cancel: '取消',
    Save: '保存',
    Upload: '上传',
    Retry: '重试',
    Reminder: '温馨提示',
    Disable: '禁用',
    Enable: '启用',
    Shrink: '收起',
    Open: '展开',
    Search: '搜索',
    Reset: '重置',
    To: '至',
    None: '无',
    Unknown: '未知',
    Weigh: '权重',
    'Drag sort': '拖动排序',
    'Save and edit next item': '保存并编辑下一项',
    'Quick search placeholder': '通过{fields}模糊搜索',
    'Please select field': '请选择{field}',
    'Please input field': '请输入{field}',
    'Please enter the correct field': '请输入正确的{field}',
    'Update time': '更新时间',
    'Create time': '创建时间',
    'Fuzzy query': '模糊查询',
    'Click select': '点击选择',
    'Edit selected row': '编辑选中行',
    'Delete selected row': '删除选中行',
    'Are you sure to delete the selected record?': '确定删除选中的记录吗？',
    'All submenus': '全部子菜单',
    'Shrink all': '收起全部',
    'Expand all': '展开全部',
    'Expand generic search': '展开公共搜索',
    'Link address': '链接地址',
    noTitle: '未命名菜单',
    '401.noPowerTip': '抱歉，当前账号没有访问该页面的权限。',
    '404.problems tip': '页面开小差了，请稍后再试。',
    '404.We will automatically return to the previous page when we are finished': '倒计时结束后将自动返回上一页',
    '404.Back to previous page': '返回上一页',
    '404.Return to home page': '返回首页',
    'axios.Operation successful': '操作成功',
    'axios.Abnormal problem, please contact the website administrator!': '发生异常，请联系网站管理员',
    'axios.Incorrect parameter!': '请求参数错误',
    'axios.You do not have permission to operate!': '您没有操作权限',
    'axios.Error requesting address:': '请求地址错误：',
    'axios.Request timed out!': '请求超时',
    'axios.Server internal error!': '服务器内部错误',
    'axios.Network request timeout!': '网络请求超时',
    'axios.Server exception!': '服务器异常',
    'axios.You are disconnected!': '当前网络已断开',
    'validate.Please enter the correct mobile number': '请输入正确的手机号',
    'validate.Please enter the correct ID number': '请输入正确的身份证号',
    'validate.Please enter the correct account': '请输入正确的账号',
    'validate.Please enter the correct password': '请输入正确的密码',
    'validate.Please enter the correct name': '请输入正确的名称',
    'validate.Content cannot be empty': '内容不能为空',
    'validate.required': '必填',
    'validate.editor required': '富文本必填',
    'validate.number': '数字',
    'validate.integer': '整数',
    'validate.float': '浮点数',
    'utils.choice': '选择文件',
    'utils.Icon': '图标',
    'utils.Ali iconcont Icon': '阿里图标',
    'utils.Local icon title': '本地图标',
    'utils.No data': '暂无数据',
    'utils.Please install editor': '请先安装编辑器',
    'utils.open': '开启',
    'utils.close': '关闭',
    'utils.Loading': '加载中...',
    'utils.Reload': '重新加载',
    'utils.The data of the uploaded file is incomplete!': '上传文件数据不完整',
    'utils.The type of uploaded file is not allowed!': '上传文件类型不允许',
    'utils.The size of the uploaded file exceeds the allowed range!': '上传文件大小超出允许范围',
    'utils.Var': '变量',
    'utils.Name': '名称',
    'utils.Title': '标题',
    'utils.type': '类型',
    'utils.Tip': '提示',
    'utils.Rule': '规则',
    'utils.Extend': '扩展',
    'utils.Dict': '字典',
    'utils.One line at a time, without quotation marks, for example: key1=value1': '每行一项，不加引号，例如：key1=value1',
    'utils.One attribute per line without quotation marks(formitem)': '每行一个属性，不加引号（FormItem）',
    'utils.Extended properties of Input, one line without quotation marks, such as: size=large': 'Input 扩展属性每行一个，不加引号，例如：size=large',
    'utils.No child menu to jump to!': '没有可跳转的子菜单',
    'utils.Navigation failed, navigation guard intercepted!': '导航失败，导航守卫已拦截',
    'utils.Navigation failed, it is at the navigation target position!': '导航失败，当前已在目标位置',
    'utils.Navigation failed, invalid route!': '导航失败，无效的路由地址',
    'utils.Navigation failed, the menu type is unrecognized!': '导航失败，无法识别的菜单类型',
    'utils.The moving position is beyond the movable range!': '移动位置超出可移动范围',
    'utils.mobile': '手机号',
    'utils.Id number': '身份证号',
    'utils.account': '账号',
    'utils.password': '密码',
    'utils.variable name': '变量名',
    'utils.email': '邮箱',
    'utils.date': '日期',
    'utils.Please select an icon': '请选择图标',
    'utils.comma': '，',
    'utils.Late at night, pay attention to your body!': '夜深了，注意休息！',
    'utils.good morning!': '早安',
    'utils.Good morning!': '上午好',
    'utils.Good noon!': '中午好',
    'utils.good afternoon': '下午好',
    'utils.Good evening': '晚上好',
    'utils.Hello!': '你好',
    'utils.welcome back': '，欢迎回来',
    'layouts.Exit full screen': '退出全屏',
    'layouts.Profile': '个人资料',
    'layouts.Logout': '退出登录',
    'layouts.Full screen is not supported': '当前浏览器不支持全屏',
    'layouts.Layout configuration': '布局配置',
    'layouts.Layout mode': '布局模式',
    'layouts.default': '默认',
    'layouts.classic': '经典',
    'layouts.Single column': '单栏',
    'layouts.Double column': '双栏',
    'layouts.overall situation': '整体设置',
    'layouts.Dark mode': '深色模式',
    'layouts.Background page switching animation': '页面切换动画',
    'layouts.Please select an animation name': '请选择动画名称',
    'layouts.sidebar': '侧边栏',
    'layouts.Side menu bar background color': '侧边栏背景色',
    'layouts.Side menu text color': '侧边栏文字颜色',
    'layouts.Side menu active item background color': '侧边栏激活项背景色',
    'layouts.Side menu active item text color': '侧边栏激活项文字颜色',
    'layouts.Side menu hover background color': '侧边栏悬停背景色',
    'layouts.Show side menu top bar (logo bar)': '显示侧边栏顶部区域',
    'layouts.Side menu top bar background color': '侧边栏顶部背景色',
    'layouts.Side menu width (when expanded)': '侧边栏宽度（展开时）',
    'layouts.Side menu default icon': '侧边栏默认图标',
    'layouts.Side menu horizontal collapse': '侧边栏横向收起',
    'layouts.Side menu accordion': '侧边栏手风琴模式',
    'layouts.Top bar': '顶部栏',
    'layouts.Top bar background color': '顶部栏背景色',
    'layouts.Top bar text color': '顶部栏文字颜色',
    'layouts.Background color when hovering over the top bar': '顶部栏悬停背景色',
    'layouts.Top bar menu active item background color': '顶部栏激活项背景色',
    'layouts.Top bar menu active item text color': '顶部栏激活项文字颜色',
    'layouts.Are you sure you want to restore all configurations to the default values?': '确定恢复所有配置为默认值吗？',
    'layouts.Restore default': '恢复默认',
    'login.Please enter an account': '请输入账号',
    'login.Please input a password': '请输入密码',
    'login.Hold session': '保持会话',
    'login.Sign in': '登录',
    'dashboard.You have worked today': '你今天已经工作了 ',
    'dashboard.Continue to work': '继续工作',
    'dashboard.have a bit of rest': '休息一会儿',
    'dashboard.Member registration': '会员注册数',
    'dashboard.Number of attachments Uploaded': '上传附件数',
    'dashboard.Total number of members': '会员总数',
    'dashboard.Number of installed plug-ins': '已安装插件数',
    'dashboard.Membership growth': '会员增长趋势',
    'dashboard.Annex growth': '附件增长趋势',
    'dashboard.New member': '新会员',
    'dashboard.Joined us': '加入我们',
    'dashboard.Member source': '会员来源',
    'dashboard.Member last name': '会员姓氏分布',
    'dashboard.Monday': '周一',
    'dashboard.Tuesday': '周二',
    'dashboard.Wednesday': '周三',
    'dashboard.Thursday': '周四',
    'dashboard.Friday': '周五',
    'dashboard.Saturday': '周六',
    'dashboard.Sunday': '周日',
    'dashboard.Visits': '访问量',
    'dashboard.Registration volume': '注册量',
    'dashboard.picture': '图片',
    'dashboard.file': '文件',
    'dashboard.table': '表格',
    'dashboard.Compressed package': '压缩包',
    'dashboard.other': '其他',
    'dashboard.Baidu': '百度',
    'dashboard.Direct access': '直接访问',
    'dashboard.take a plane': '飞机出行',
    'dashboard.Take the high-speed railway': '高铁出行',
    'dashboard.full name': '全名',
    'dashboard.hour': '时',
    'dashboard.minute': '分',
    'dashboard.second': '秒',
    'dashboard.day': '天',
    'auth.admin.username': '管理员账号',
    'auth.admin.nickname': '管理员昵称',
    'auth.admin.group': '所属角色组',
    'auth.admin.avatar': '头像',
    'auth.admin.email': '邮箱',
    'auth.admin.mobile': '手机号',
    'auth.admin.Last login': '最后登录时间',
    'auth.admin.Password': '密码',
    'auth.admin.Administrator login': '请输入管理员登录账号',
    'auth.admin.Please leave blank if not modified': '如不修改请留空',
    'auth.admin.Personal signature': '个性签名',
    'auth.group.Manage subordinate role groups here': '可在这里管理当前账号可见的下级角色组',
    'auth.group.GroupName': '角色组名称',
    'auth.group.Group name': '角色组名称',
    'auth.group.Parent group': '上级角色组',
    'auth.group.The parent group cannot be the group itself': '上级角色组不能选择自己',
    'auth.group.jurisdiction': '权限',
    'auth.adminLog.admin_id': '管理员 ID',
    'auth.adminLog.data': '请求数据',
    'auth.adminLog.ip': '操作 IP',
    'auth.adminLog.Operation administrator': '操作管理员',
    'auth.adminLog.Operator IP': '操作 IP',
    'auth.adminLog.Request data': '请求数据',
    'auth.adminLog.title': '日志标题',
    'auth.adminLog.url': '请求地址',
    'auth.adminLog.useragent': 'User Agent',
    'auth.adminLog.username': '管理员账号',
    'auth.rule.title': '规则标题',
    'auth.rule.Icon': '图标',
    'auth.rule.name': '规则标识',
    'auth.rule.type': '规则类型',
    'auth.rule.type menu': '菜单',
    'auth.rule.type menu_dir': '目录',
    'auth.rule.type button': '按钮',
    'auth.rule.cache': '缓存',
    'auth.rule.Add as menu only': '仅新增菜单',
    'auth.rule.Add as route only': '仅新增路由',
    'auth.rule.Component path': '组件路径',
    'auth.rule.Create Page Button': '生成页面按钮',
    'auth.rule.Create Page Button add': '新增',
    'auth.rule.Create Page Button del': '删除',
    'auth.rule.Create Page Button edit': '编辑',
    'auth.rule.Create Page Button index': '列表',
    'auth.rule.Create Page Button sortable': '排序',
    'auth.rule.Create Page Button tips': '自动生成页面时创建需要的按钮',
    'auth.rule.English name, which does not need to start with `/admin`, such as auth/menu': '英文名称，无需以 `/admin` 开头，例如 auth/menu',
    'auth.rule.extend Title': '扩展类型',
    'auth.rule.Extended properties': '扩展属性',
    'auth.rule.It will be registered as the web side routing name and used as the server side API authentication':
        '将注册为前端路由名称，并用于服务端 API 权限校验',
    'auth.rule.Link address': '链接地址',
    'auth.rule.Menu type': '菜单类型',
    'auth.rule.Menu type link (offsite)': '外链',
    'auth.rule.Menu type tab': '选项卡',
    'auth.rule.none': '无',
    'auth.rule.Please enter the correct URL': '请输入正确的 URL',
    'auth.rule.Please enter the URL address of the link or iframe': '请输入链接或 iframe 的 URL 地址',
    'auth.rule.Please enter the weight of menu rule (sort by)': '请输入菜单规则权重（用于排序）',
    'auth.rule.Please select the button for automatically creating the desired page': '请选择需要自动创建的页面按钮',
    'auth.rule.Routing path': '路由路径',
    'auth.rule.Rule comments': '规则备注',
    'auth.rule.Rule Icon': '规则图标',
    'auth.rule.Rule name': '规则标识',
    'auth.rule.Rule title': '规则标题',
    'auth.rule.Rule type': '规则类型',
    'auth.rule.Rule weight': '规则权重',
    'auth.rule.Superior menu rule': '上级菜单规则',
    'auth.rule.The superior menu rule cannot be the rule itself': '上级菜单规则不能选择自己',
    'auth.rule.The web side routing path (path) does not need to start with `/admin`, such as auth/menu':
        '前端路由路径无需以 `/admin` 开头，例如 auth/menu',
    'auth.rule.Web side component path, please start with /src, such as: /src/views/dashboard':
        '前端组件路径请以 /src 开头，例如 /src/views/dashboard',
    'routine.adminInfo.autograph': '个性签名',
    'routine.adminInfo.e-mail address': '邮箱地址',
    'routine.adminInfo.Last logged in on': '最后登录时间',
    'routine.adminInfo.New password': '新密码',
    'routine.adminInfo.Operation log': '操作日志',
    'routine.adminInfo.phone number': '手机号',
    'routine.adminInfo.Please enter a nickname': '请输入昵称',
    'routine.adminInfo.Please leave blank if not modified': '如不修改请留空',
    'routine.adminInfo.Save changes': '保存修改',
    'routine.adminInfo.This guy is lazy and doesn write anything': '这个人很懒，什么都没留下',
    'routine.adminInfo.user name': '用户名',
    'routine.adminInfo.User nickname': '用户昵称',
    'utils.ArrayKey': '键名',
    'utils.ArrayValue': '键值',
    'utils.Breakdown': '分类',
    'utils.Select File': '选择文件',
    'utils.Original name': '原始名称',
    'utils.You can also select': '你还可以选择',
    'utils.items': '项',
    'utils.Last upload time': '最后上传时间',
    'utils.preview': '预览',
    'utils.size': '大小',
    'utils.Upload (Reference) times': '上传（引用）次数',
    'No AwesomeIcon style sheet': '未检测到 Font Awesome 样式文件',
    'No ElementPlus Icons': '未检测到 Element Plus 图标',
    'No Iconfont style sheet': '未检测到 Iconfont 样式文件',
    'No Local Icons': '未检测到本地图标',
}

const interpolate = (template: string, named: Record<string, unknown>) => {
    return template.replace(/\{(\w+)\}/g, (_, key: string) => String(named[key] ?? `{${key}}`))
}

export const hasTranslation = (key: string) => key in messages

export const translate = (key: string, named: Record<string, unknown> = {}) => {
    const template = messages[key] ?? key
    return Object.keys(named).length ? interpolate(template, named) : template
}

export default translate
