create table if not exists admins (
    id integer generated by default as identity primary key,
    username text not null unique,
    nickname text not null,
    avatar text not null,
    email text not null default '',
    mobile text not null default '',
    motto text not null default '',
    password_hash text not null,
    status text not null default 'enable',
    is_super integer not null default 0,
    last_login_time text not null,
    create_time text not null,
    update_time text not null
);

create table if not exists groups (
    id integer generated by default as identity primary key,
    pid integer not null default 0,
    name text not null,
    status integer not null default 1,
    create_time text not null,
    update_time text not null
);

create table if not exists rules (
    id integer generated by default as identity primary key,
    pid integer not null default 0,
    type text not null,
    title text not null,
    name text not null,
    path text not null default '',
    icon text not null default '',
    menu_type text,
    component text,
    keepalive integer not null default 0,
    extend text not null default 'none',
    url text,
    status integer not null default 1,
    weigh integer not null default 0,
    remark text not null default '',
    buttons jsonb,
    create_time text not null,
    update_time text not null
);

create table if not exists admin_groups (
    admin_id integer not null references admins(id) on delete cascade,
    group_id integer not null references groups(id) on delete cascade,
    primary key (admin_id, group_id)
);

create table if not exists group_rules (
    group_id integer not null references groups(id) on delete cascade,
    rule_id integer not null,
    primary key (group_id, rule_id)
);

create table if not exists admin_logs (
    id integer generated by default as identity primary key,
    admin_id integer not null,
    username text not null,
    title text not null,
    url text not null,
    ip text not null,
    useragent text not null,
    create_time text not null,
    data text not null default '{}'
);

create table if not exists attachments (
    id integer generated by default as identity primary key,
    topic text not null,
    url text not null,
    full_url text not null,
    suffix text not null,
    mimetype text not null,
    size integer not null default 0,
    quote integer not null default 0,
    name text not null,
    storage_path text,
    last_upload_time text not null,
    create_time text not null
);

create table if not exists sessions (
    id text primary key,
    admin_id integer not null references admins(id) on delete cascade,
    access_token text not null unique,
    refresh_token text not null unique,
    access_expires_at text not null,
    refresh_expires_at text not null,
    ip text not null default '',
    useragent text not null default '',
    created_at text not null,
    updated_at text not null,
    revoked_at text
);
