export const ADMIN_INFO = 'adminInfo'
export const STORE_CONFIG = 'storeConfig_v2'
export const STORE_TAB_VIEW_CONFIG = 'storeTabViewConfig'
export const WORKING_TIME = 'workingTime'
export const BEFORE_RESIZE_LAYOUT = 'beforeResizeLayout'
